### ISSUE TITLE
Database: DB tasks

### ISSUE THREAD

**Issue by jamesjmeyer210** [adlistergroupproject/GroupAdlister#4]
- [x] Improve the initial sql script
    - [x] Create one user in the init script
    - [x] Create a categories table
- [x] Create a seeder script

**Comment by LexiPedrottiMorgan** [comment]
- [x] add a viewsCount column to keep track of how many times each ad has been viewed so i can display that

**Comment by jamesjmeyer210** [comment]
The database initialization is complete.
